### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'train'

### ISSUE THREAD

**Issue by liufh1** [fangwei123456/Parallel-Spiking-Neuron#2]
您好！
我尝试运行CIFAR10DVS数据集中的代码。我已经安装好相关依赖
当我运行
python train_vgg.py -b 32 --epochs 200 -method PSN -TET -T 10
时，会报以下错误：
Traceback (most recent call last):
  File "train_vgg.py", line 145, in <module>
    train_dataset, val_dataset = build_dvscifar()
  File "train_vgg.py", line 138, in build_dvscifar
    train_set = CIFAR10DVS(root='../dataset', train=True, data_type='frame', frames_number=args.T, split_by='number', transform=transform_train)

请问该如何解决呢？
谢谢！

**Comment by fangwei123456** [comment]
检查一下是否按照里面的readme安装特定版本的SJ框架

**Comment by liufh1** [comment]
好的，谢谢
